apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: klinik-auto
  namespace: learning-helm
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: klinik-repo
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@yourdomain.com
        name: fluxcdbot
    push:
      branch: main
  update:
    strategy: Setters

